# Test against the latest version of this Node.js version
environment:
  nodejs_version: "10"

cache:
    - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run release -- --win --x64

# Don't actually build.
build: off