matrix:
  include:
    - os: linux
      dist: trusty
sudo: required

language: node_js

install:
  - npm install -g npm@latest
  - npm install

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run release -- --linux; fi

cache:
  directories:
    - node_modules